fixing code to upload the artifact from build job

diff --git a/.github/workflows/promote_package.yml b/.github/workflows/promote_package.yml
--- a/.github/workflows/promote_package.yml
+++ b/.github/workflows/promote_package.yml
@@ -13,7 +13,7 @@ env:
   CLOUDSMITH_STAGING_REPO: 'staging'
   CLOUDSMITH_PRODUCTION_REPO: 'production'
   CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
-  PACKAGE_NAME: 'example_package'
+  PACKAGE_NAME: 'example-package'
 
 jobs:
   promote:
@@ -55,20 +55,22 @@ jobs:
       - name: Tag Package as Ready for Production
         run: |
           echo "Tagging package with 'ready-for-production'..."
-          PACKAGE_QUERY="filename:${PACKAGE_NAME}-${{ github.event.client_payload.package_version }}.tar.gz"
+          PACKAGE_QUERY="name:example_package AND version:${{ github.event.client_payload.package_version }}"
+    
           PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
-            --api-key $CLOUDSMITH_API_KEY \
-            -q "$PACKAGE_QUERY" -F json)
-          
+          --api-key $CLOUDSMITH_API_KEY \
+          -q "$PACKAGE_QUERY" -F json)
+
           IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')
-          
+
           if [ "$IDENTIFIER" = "null" ] || [ -z "$IDENTIFIER" ]; then
-            echo "ERROR: Package not found in staging!"
-            exit 1
+          echo "ERROR: Package not found in staging!"
+          exit 1
           fi
-          
+    
           cloudsmith tag add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
-            ready-for-production --api-key $CLOUDSMITH_API_KEY
+          ready-for-production --api-key $CLOUDSMITH_API_KEY
+
 
       - name: Promote Package to Production
         run: |
